- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-{{ dev_environment }}-vpc"
        cidr_block: "200.1.0.0/16"
        dns_hostnames: yes
        dns_support: yes
        tags:
          Name: "{{ name }}-{{ dev_environment }}-vpc"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: vpc_name

    - name: debug vpc
      debug:
        var: vpc_name
    # Security Group for EC2 #
    - name: Create required SSH SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-ssh-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "SSH ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:
              - 217.24.19.64/29
              - 82.117.216.88/30
              - 15.188.31.234/32
          - proto: tcp
            from_port: 15672
            to_port: 15672
            cidr_ip:
              - 217.24.19.69/29
              - 82.117.216.88/30
          - proto: tcp
            from_port: 10050
            to_port: 10050
            cidr_ip:
              - 217.24.19.69/29
              - 82.117.216.88/30
              - 34.254.36.247/32
              - 50.16.146.15/32
        rules_egress:
          - proto: "-1"
            from_port: 0
            to_port: 0
            cidr_ip: "0.0.0.0/0"
        tags:
          Name: "{{ name }}-ssh-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"

    # Define RDS Postgresql Security Group #
    - name: Create required EC2 Web SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-web-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "Web ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "0.0.0.0/0"
        rules_egress:
          - proto: "-1"
            from_port: 0
            to_port: 0
            cidr_ip: "0.0.0.0/0"
        tags:
          Name: "{{ name }}-web-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"

    # Define RDS Postgresql Security Group #
    - name: Create required RDS Postgres SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-db-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "DB ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip:
              - 200.1.0.0/16
              - 217.24.19.64/2
              - 82.117.216.88/30
        tags:
          Name: "{{ name }}-db-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
