- name: Setup Octopus Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    chat: "{{ lookup('env','var_chat') }}"
    signaling: "{{ lookup('env','var_signaling') }}"
    analytics: "{{ lookup('env','var_analytics') }}"
    ecommerce: "{{ lookup('env','var_ecommerce') }}"
    comments: "{{ lookup('env','var_comments') }}"
    webpay: "{{ lookup('env','var_webpay') }}"
    ums: "{{ lookup('env','var_ums') }}"
  roles:
    - common
    - octopus-server
    - octopus-octopush
    - webapp
    - { role: octopus-chat, when: chat == '1' }
    - { role: octopus-comments, when: comments == '1' }
    - { role: octopus-analytics, when: analytics == '1' }
    - { role: octopus-ecommerce, when: ecommerce == '1' }
    - { role: webpay, when: webpay == '1' }
    - { role: ums-server, when: ums == '1' }
    - { role: signaling-server, when: signaling == '1' }
    - nginx
    - docker_containers
