- hosts: localhost
  gather_facts: no
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','var_aws_access_key') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','var_aws_secret_key') }}"
    AWS_REGION: "{{ lookup('env','var_region') }}"
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
  tasks:
    # Gather EC2 Instance Facts #
    - name: Gather EC2 Facts
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:user:client": "{{ var_name }}"
      register: ec2_facts

    # Terminate EC2 Instances #
    - name: Terminate all {{ var_name }}-{{ dev_environment }} EC2 instances
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        instance_ids: "{{ item.instance_id }}"
      with_items: "{{ ec2_facts.instances }}"

    # Terminate RDS Instances #
    - name: Terminate {{ var_name }}-{{ dev_environment }} RDS instance
      rds:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        command: delete
        instance_name: "{{ var_name }}-{{ dev_environment }}-all-db"
        snapshot: "{{ var_name }}-{{ dev_environment }}-all-db"

    # Delete S3 Buckets #
    - name: Delete all {{ var_name }}-{{ dev_environment }} S3 buckets
      s3_bucket:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        name: "{{ item }}"
        force: yes
      loop:
        - "{{ var_name }}-{{ dev_environment }}-octopus-server"
        - "{{ var_name }}-{{ dev_environment }}-private-octopus-server-s3"
        - "{{ var_name }}-{{ dev_environment }}-chat-server-user-attachments"
        - "{{ var_name }}-{{ dev_environment }}-chat-server-canned-attachments"
        - "{{ var_name }}-{{ dev_environment }}-ecommerce-s3"
        - "{{ var_name }}-{{ dev_environment }}-private-ecommerce-s3"

    # Wait for RDS instances to terminate #
    - name: Sleep for 10 minutes
      command: "sleep 600"

    # Gather facts for SG #
    - name: Gather SG Facts
      ec2_group_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:user:client": "{{ var_name }}"
      register: sg_facts

    - name: Debug SG Facts
      debug:
        var: sg_facts

    # Remove SG #
    - name: Remove {{ var_name }}-{{ dev_environment }} SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        group_id: "{{ item.group_id }}"
      with_items: "{{ sg_facts.security_groups }}"

    # Gather VPC Facts #
    - name: Gather VPC Facts
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:user:client": "{{ var_name }}"
      register: vpc_facts

    # Delete IG #
    - name: Remove {{ var_name }}-{{ dev_environment }} IG
      ec2_vpc_igw:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        vpc_id: "{{ vpc_facts.vpcs[0].id }}"

    # Gather Subnet Facts #
    - name: Gather Subnet Facts
      ec2_vpc_subnet_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:user:client": "{{ var_name }}"
      register: subnet_facts

    - name: Debug Subnet Facts
      debug:
        var: subnet_facts

    # Delete Subnets #
    - name: Remove {{ var_name }}-{{ dev_environment }} Subnets
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        vpc_id: "{{ subnet_facts.subnets[0].vpc_id }}"
        cidr: "{{ item }}"
      with_items:
        - 200.1.1.0/24
        - 200.1.2.0/24

    # Delete RDS Subnet Group #
    - name: Remove {{ var_name }}-{{ dev_environment }} RDS Subnet Group
      rds_subnet_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        name: "{{ var_name }}-subnet-db-public"

    # Gather RT Facts #
    - name: Gather RT Facts
      ec2_vpc_route_table_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:user:client": "{{ var_name }}"
      register: rt_facts

    # Delete RT #
    - name: Remove {{ var_name }}-{{ dev_environment }} RT
      ec2_vpc_route_table:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        vpc_id: "{{ rt_facts.route_tables[0].vpc_id }}"
        route_table_id: "{{ rt_facts.route_tables[0].id }}"
        lookup: id

    # Delete VPC #
    - name: Remove {{ var_name }}-{{ dev_environment }} VPC
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: absent
        name: "{{ var_name }}-{{ dev_environment }}-vpc"
        cidr_block: "{{ vpc_facts.vpcs[0].cidr_block }}"
