--- # Prepare directories

- name: Create directory structure
  file: 
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0755 
    state: directory
  with_items:
    - /carnegie/backup/deployment
    - /carnegie/shelf/{{ service }}
    - /carnegie/services/{{ service }}

- name: Unpack archive
  unarchive:
    src: /tmp/ums/ums.tar
    dest: /carnegie/services/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"
    list_files: true
    mode: 0755 

- name: Configure
  template: 
    src: ums.service.j2
    dest: /etc/init.d/{{ service }}
    owner: root
    group: root
    mode: 0755
  
- name: Enable ums and daemon reload
  systemd:
    name: ums
    enabled: yes
    daemon_reload: yes