---
# Condition for vm.commit.memory - RabbitMQ
- name: Check does redis directory exists
  stat:
    path: /carnegie/docker-compose/rabbitmq
  register: dir_rabbit

# Condition for THP Pages - Redis
- name: Check does redis directory exists
  stat:
    path: /carnegie/docker-compose/redis
  register: dir_redis

# Needed for RabbitMQ
- name: Recommended to set the Linux kernel overcommit memory settings
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes
  when: dir_rabbit.stat.exists

# Transparent Huge Pages (causes latency and mem usage issues with redis) - need to disable
- name: Disable THP in kernel
  template:
    src: "redis/disable-transparent-huge-pages.service"
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0755
  when: dir_redis.stat.exists

- name: Start, Enable service disable-transparent-huge-pages.service
  systemd:
    daemon_reload: yes
    name: disable-transparent-huge-pages.service
    state: started
    enabled: yes
  when: dir_redis.stat.exists
  ignore_errors: yes

- name: Prepare repository to download required packages
  yum:
    name: epel-release
    state: present
  when: ansible_facts['distribution'] == 'Amazon'
