version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: "{{ var_name }}-rabbitmq-server"
    hostname: "{{ var_name }}-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: devops-servicechat
      RABBITMQ_DEFAULT_PASS: devops-service123ChAtbREStrikalaMiBaka
    volumes:
      - /devops/docker-compose/rabbitmq/data-rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
