- hosts: localhost
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  vars_files:
    - keys.yml
  # vars:
  #   aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
  #   aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
  #vars:
  #   aws_access_key: "{{ lookup('env','var_aws_access_key') }}"
  #   aws_secret_key: "{{ lookup('env','var_aws_secret_key') }}"
  #   region: "{{ lookup('env','var_region') }}"
  #   env: "{{ lookup('env','var_environment') }}"
  #   dev_environment: "{{ lookup('env','var_dev_environment') }}"
  #   name: "{{ lookup('env','var_name') }}"
  #   db_username: "{{ lookup('env','var_db_username') }}" #octopusinfluencer
  #   db_password: "{{ lookup('env','var_db_password') }}" #"CarnegieInfluencer!12"
  #   chat: "{{ lookup('env','var_chat') }}"
  #   ads: "{{ lookup('env','var_ads') }}"
  #   signaling: "{{ lookup('env','var_signaling') }}"
  #   analytics: "{{ lookup('env','var_analytics') }}"
  #   reports: "{{ lookup('env','var_reports') }}"
  #   ecommerce: "{{ lookup('env','var_ecommerce') }}"
  #   comments: "{{ lookup('env','var_comments') }}"
  #   transcoder: "{{ lookup('env','var_transcoder') }}"
  #   webpay: "{{ lookup('env','var_webpay') }}"
  #   ums: "{{ lookup('env','var_ums') }}"
  # roles:
  #   - common
  #   - octopus-server
  #   - octopus-octopush
  #   - webapp
  #   - { role: octopus-chat, when: chat == '1' }
  #   - { role: octopus-comments, when: comments == '1' }
  #   - { role: octopus-analytics, when: analytics == '1' }
  #   - { role: octopus-ecommerce, when: ecommerce == '1' }
  #   - { role: webpay, when: webpay == '1' }
  #   - { role: ums-server, when: ums == '1' }
  #   - { role: signaling-server, when: signaling == '1' }
  #   - docker_containers
  #   - nginx
  tasks:
    # VPC #
    - name: Create VPC
      ec2_vpc_net:
        name: "{{ name }}-{{ dev_environment }}-vpc"
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        cidr_block: "200.1.0.0/16"
        dns_hostnames: yes
        dns_support: yes
        tags:
          Name: "{{ name }}-{{ dev_environment }}-vpc"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: vpc_name

    - name: Debug VPC
      debug:
        var: vpc_name

    # AMI Image Facts #
    - name: Obtain all AZ present in region {{ AWS_REGION }}
      aws_az_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
      register: az_in_region

    - name: Display all AZ present in region {{ AWS_REGION }}
      debug:
        var: az_in_region

    # Subnet 1 #
    - name: Create Subnet 1
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        vpc_id: "{{ vpc_name.vpc.id }}"
        cidr: "200.1.1.0/24"
        az: "{{ az_in_region.availability_zones[0].zone_name }}"
        map_public: yes
        tags:
          Name: "{{ name }}-{{ dev_environment }}-public-subnet-1"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: public_subnet_1

    - name: Debug Subnet 1
      debug:
        var: public_subnet_1

    # Subnet 2 #
    - name: Create Subnet 2
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        vpc_id: "{{ vpc_name.vpc.id }}"
        cidr: "200.1.2.0/24"
        az: "{{ az_in_region.availability_zones[1].zone_name }}"
        map_public: yes
        tags:
          Name: "{{ name }}-{{ dev_environment }}-public-subnet-2"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: public_subnet_2

    - name: Debug Subnet 2
      debug:
        var: public_subnet_2

    # Internet Gateway #
    - name: Create Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        vpc_id: "{{ vpc_name.vpc.id }}"
        state: present
        tags:
          Name: "{{ name }}-{{ dev_environment }}-igw"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: igw

    # Routing Table #
    - name: Create Routing Table
      ec2_vpc_route_table:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        vpc_id: "{{ vpc_name.vpc.id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.gateway_id }}"
        subnets:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
        tags:
          Name: "{{ name }}-{{ dev_environment }}-rt"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: rt

    # Security Group for EC2 #
    - name: Create required SSH SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-ssh-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "SSH ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:
              - 217.24.19.64/29
              - 82.117.216.88/30
              - 15.188.31.234/32
          - proto: tcp
            from_port: 15672
            to_port: 15672
            cidr_ip:
              - 217.24.19.64/29
              - 82.117.216.88/30
          - proto: tcp
            from_port: 10050
            to_port: 10050
            cidr_ip:
              - 217.24.19.69/29
              - 82.117.216.88/30
              - 34.254.36.247/32
              - 50.16.146.15/32
          - proto: tcp
            from_port: 0
            to_port: 0
            cidr_ip:
              - "200.1.0.0/16"
        rules_egress:
          - proto: "-1"
            from_port: 0
            to_port: 0
            cidr_ip: "0.0.0.0/0"
        tags:
          Name: "{{ name }}-ssh-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"

    # Define EC2 Postgresql Security Group #
    - name: Create required EC2 Web SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-web-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "Web ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "0.0.0.0/0"
        rules_egress:
          - proto: "-1"
            from_port: 0
            to_port: 0
            cidr_ip: "0.0.0.0/0"
        tags:
          Name: "{{ name }}-web-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"

    # Define RDS Postgresql Security Group #
    - name: Create required RDS Postgres SG
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ name }}-db-sg"
        vpc_id: "{{ vpc_name.vpc.id }}"
        description: "DB ports for EC2 single server"
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip:
              - 200.1.0.0/16
              - 217.24.19.64/29
              - 82.117.216.88/30
          - proto: tcp
            from_port: 10050
            to_port: 10050
            cidr_ip:
              - 217.24.19.69/29
              - 82.117.216.88/30
              - 34.254.36.247/32
              - 50.16.146.15/32
        rules_egress:
          - proto: -1
            from_port: 0
            to_port: 0
            cidr_ip: "0.0.0.0/0"
        tags:
          Name: "{{ name }}-db-sg"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: db_sg

    - name: Debug a DB SG
      debug:
        var: db_sg

    # Get AWS ami image id #
    - name: Get the AMI image id
      ec2_ami_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          name: "amzn2-ami-hvm-*-x86_64-gp2"
      register: ami_find

    - name: Sort the latest AMI
      set_fact:
        latest_ami: "{{ ami_find.images | sort(attribute='creation_date') | last }}"

    - name: Debug the AMI image
      debug:
        var: latest_ami

    # Create AWS keypair #
    - name: Create aws private keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: carnegie1
        key_material: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5IkRNJQtrROT8pjKJeoA8lF7wQ6wfIcj4xxE/nRc19xTebwOMlYfpfTRfSk65FjFkf0xLuDTpa8r/dA+tmkMkj3oCFR+UKCyTFyhxWbRvVzaRckk+ph8BcENNMHd8uAAukBnHlJiPwI1+BCaSNR1LhUGTRBiiTJMK8dxfBHnfGfSm3s7j8yVQbYcGk8GC8cYk5m6ZfF3UBeD0/P6mdx0eIKCGkfk2yWFHOK+BAJgwC0GNPChxHY07ywBk7+X7fIj3+ldyXIH+vtBkx6nWXJ1nw9zz1mFCa9QziybsglcOS//zKxmQ4lAVOcul4xpiY6fODHtXKS2RB1dm0ADKuDUb CarnegieKey"

    # Create EC2 octopus instance #
    - name: Change octopus instance state by tag
      amazon.aws.ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        key_name: carnegie1
        instance_type: "{{ i_type }}"
        image: "{{ latest_ami.image_id }}"
        group:
          - "{{ name }}-ssh-sg"
          - "{{ name }}-web-sg"
        wait: yes
        wait_timeout: 500
        assign_public_ip: yes
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 20
            tags:
              Name: "{{ name }}-{{ dev_environment }}-volume"
              user:client: "{{ name }}"
              user:Environment: "{{ dev_environment }}"
        instance_tags:
          Name: "{{ name }}-{{ dev_environment }}-all"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
        exact_count: 1
        count_tag:
          Name: "{{ name }}-{{ dev_environment }}-all"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: ec2_var

    # - name: Install octopus services on EC2 octopus instance
    #   command: "ansible-playbook -u ec2-user -i 46.137.53.186, --private-key ~/.ssh/carnegie1.pem octopus_setup.yml"
    #   register: octopus_setup

    # - name: Debug octopus_setup
    #   debug:
    #     var: octopus_setup

    # Create EC2 transcoder instance #
    - name: Change transcoder instance stage by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        key_name: carnegie1
        instance_type: "{{ i_type }}"
        image: "{{ latest_ami.image_id }}"
        group:
          - "{{ name }}-ssh-sg"
          - "{{ name }}-web-sg"
        wait: yes
        wait_timeout: 500
        assign_public_ip: yes
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 20
            tags:
              Name: "{{ name }}-{{ dev_environment }}-transcoder-volume"
              user:client: "{{ name }}"
              user:Environment: "{{ dev_environment }}"
        instance_tags:
          Name: "{{ name }}-{{ dev_environment }}-transcoder"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
        exact_count: 1
        count_tag:
          Name: "{{ name }}-{{ dev_environment }}-transcoder"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"

    # Create RDS Postgresql subnet group #
    - name: Create RDS subnet group
      rds_subnet_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: present
        name: "{{ name }}-subnet-db-public"
        description: "RDS Subnet"
        subnets:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
      register: rds_subnet_group

    - name: Debug the RDS Subnet Group
      debug:
        var: rds_subnet_group

    # Create RDS instance for octopus server #
    - name: Create RDS octopus instance
      rds:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        command: create
        db_engine: postgres
        engine_version: "9.6.11"
        db_name: "{{ name }}{{ dev_environment }}db"
        instance_name: "{{ name }}-{{ dev_environment }}-db"
        instance_type: "{{ db_type }}"
        multi_zone: no
        username: "{{ db_username }}"
        password: "{{ db_password }}"
        backup_window: "04:00-04:30"
        maint_window: "sun:04:30-sun:05:30"
        backup_retention: "7"
        publicly_accessible: yes
        port: 5432
        size: "20"
        vpc_security_groups: "{{ db_sg.group_id }}"
        subnet: "{{ name }}-subnet-db-public"
        wait: yes
        wait_timeout: 500
        tags:
          Name: "{{ name }}-{{ dev_environment }}-db-all"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
      register: rds_instance

    # Create required S3 buckets #
    - name: Create S3 buckets
      s3_bucket:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ item }}"
        state: presentr
        versioning: no
        tags:
          Name: "{{ item }}"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
        purge_tags: yes
      loop:
        - "{{ name }}-{{ dev_environment }}-octopus-server"
        - "{{ name }}-{{ dev_environment }}-private-octopus-server-s3"
        - "{{ name }}-{{ dev_environment }}-chat-server-user-attachments"
        - "{{ name }}-{{ dev_environment }}-ecommerce-s3"
        - "{{ name }}-{{ dev_environment }}-private-ecommerce-s3"
      register: s3_debug

    - name: debug S3 Bucket
      debug:
        var: s3_debug

    # Create required S3 chat-server-canned-attachments bucket #
    - name: Create S3 chat-server-canned-attachments bucket
      s3_bucket:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: "{{ item }}"
        state: present
        versioning: no
        policy: "{{ lookup('file','policy.json') }}"
        tags:
          Name: "{{ item }}"
          user:client: "{{ name }}"
          user:Environment: "{{ dev_environment }}"
        purge_tags: yes
      loop:
        - "{{ name }}-{{ dev_environment }}-chat-server-canned-attachments"
      register: s3_chat

    - name: debug S3 Chat bucket
      debug:
        var: s3_chat
    # Create CORS rules for created S3 buckets #
    # - name: Apply CORS rules to S3 buckets
    #   aws_s3_cors:
    #     name: "{{ item }}"
    #     state: present
    #     rules:
    #       - allowed_origins:
    #           - "*"
    #         allowed_methods:
    #           - GET
    #           - POST
    #           - PUT
    #           - DELETE
    #         allowed_headers:
    #           - "*"
    #         expose_headers:
    #           - ETag
    #         max_age_seconds: 3000
    #   loop:
    #     - "{{ name }}-{{ dev_environment }}-octopus-server"
    #     - "{{ name }}-{{ dev_environment }}-private-octopus-server-s3"
    #     - "{{ name }}-{{ dev_environment }}-chat-server-user-attachments"
    #     - "{{ name }}-{{ dev_environment }}-chat-server-canned-attachments"
    #     - "{{ name }}-{{ dev_environment }}-ecommerce-s3"
    #     - "{{ name }}-{{ dev_environment }}-private-ecommerce-s3"
    #   register: s3_cors
    # - name: debug S3 CORS Rules
    #   debug:
    #     var: s3_cors
