- name: Setup Octopus Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    # dev_environment: demo
    # env: small-infrastructure-environment
    # name: blizzard
    # chat: "true"
    # comments: "true"
    # analytics: "true"
    # ecommerce: "true"
    # reports: "false"
    # webpay: "true"
    # ums: "true"
    # transcoder: "true"
    # signaling: "true"
    aws_access_key: "{{ lookup('env','var_aws_access_key') }}"
    aws_secret_key: "{{ lookup('env','var_aws_secret_key') }}"
    region: "{{ lookup('env','var_region') }}"
    env: "{{ lookup('env','var_environment') }}"
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    db_username: "{{ lookup('env','var_db_username') }}"
    db_password: "{{ lookup('env','var_db_password') }}"
    chat: "{{ lookup('env','var_chat') }}"
    signaling: "{{ lookup('env','var_signaling') }}"
    analytics: "{{ lookup('env','var_analytics') }}"
    ecommerce: "{{ lookup('env','var_ecommerce') }}"
    comments: "{{ lookup('env','var_comments') }}"
    transcoder: "{{ lookup('env','var_transcoder') }}"
    webpay: "{{ lookup('env','var_webpay') }}"
    ums: "{{ lookup('env','var_ums') }}"
  roles:
    - common
    - transcoder-server
