- name: Setup Devops Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    payweb: "{{ lookup('env','var_payweb') }}"
    sign: "{{ lookup('env','var_sign') }}"
  roles:
    - common
    - trn-server
    - { role: sign-server, when: sign == '1' }
    - { role: payweb, when: payweb == '1' }
