- name: Setup Devops Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    commerce: "{{ lookup('env','var_commerce') }}"
  roles:
    - common
    - devops-service-push
    - devops-service-chat
    - devops-service-ments
    - devops-service-lyrics
    - { role: devops-service-commerce, when: commerce == '1' }
    - docker_containers
