- name: Setup Octopus Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    ecommerce: "{{ lookup('env','var_ecommerce') }}"
  roles:
    - common
    - octopus-octopush
    - octopus-chat
    - octopus-comments
    - octopus-analytics
    - { role: octopus-ecommerce, when: ecommerce == '1' }
    - docker_containers
