- name: Setup Octopus Single Server environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    webpay: "{{ lookup('env','var_webpay') }}"
    signaling: "{{ lookup('env','var_signaling') }}"
  roles:
    - common
    - transcoder-server
    - { role: signaling-server, when: signaling == '1' }
    - { role: webpay, when: webpay == '1' }
