---
- name: Setup Octopus Single Server environment
  hosts: all
  vars:
    dev_environment: "{{ lookup('env','var_dev_environment') }}"
    var_name: "{{ lookup('env','var_name') }}"
    subscription: "{{ lookup('env','var_subscription') }}"
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  roles:
    - common
    - octopus-server
    - ums-server
    - { role: octopus-subscription, when: subscription == '1' }
