--- # System configuration and updates
- name: Set hostname
  hostname:
    name: "{{ var_name }}-{{ dev_environment }}-webserver"

- name: Get nginx release
  shell: amazon-linux-extras install -y nginx1.12
  when: ansible_distribution == 'Amazon'

- name: Prepare nginx directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - /etc/nginx/ssl
    - /etc/nginx/backup

- name: Update nginx configuration
  template:
    src: nginx-lb.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
