--- # Prepare directories
- name: Create directory structure
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - /carnegie/shelf/{{ service }}
    - /carnegie/services/{{ service }}

- name: Unpack archive
  unarchive:
    src: /tmp/octopus-analytics/octopus-analytics.tar
    dest: /carnegie/services/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"
    list_files: true
    mode: 0755

- name: Configure service
  template:
    src: octopus-analytics.service.j2
    dest: /etc/init.d/{{ service }}
    owner: root
    group: root
    mode: 0755

- name: Enable octopus-analytics and daemon reload
  systemd:
    name: octopus-analytics
    enabled: yes
    daemon_reload: yes
