---
- name: Create directory structure
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - /carnegie/webapp/{{ var_name }}/mobile
    - /carnegie/webapp/{{ var_name }}/ecommerce
    - /carnegie/webapp/{{ var_name }}/.well-known
